description: TheBlacklist, with persistent storage. For more information about using
  this template, see https://github.com/gary-crowe/hitlist
name: blacklist-persistent
tags: blacklist,mysql,python
version: v0.0.1
