apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"theblacklist:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"theblacklist\")].image"}]'
  labels:
    app: theblacklist
    template: blacklist-ephemeral
  name: theblacklist
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: theblacklist
  strategy: {}
  template:
    metadata:
      annotations: null
      labels:
        deployment: theblacklist
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql_database }}
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql_password }}
        - name: MYSQL_USER
          value: {{ .Values.mysql_user }}
        image: ' '
        name: theblacklist
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"mysql:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"mysql\")].image"}]'
  labels:
    app: mysql
    template: blacklist-ephemeral
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: mysql
  template:
    metadata:
      annotations: null
      labels:
        deployment: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql_database }}
        - name: MYSQL_OPERATIONS_PASSWORD
          value: oppass
        - name: MYSQL_OPERATIONS_USER
          value: opuser
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql_password }}
        - name: MYSQL_USER
          value: {{ .Values.mysql_user }}
        image: ' '
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
