apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations: null
  labels:
    app: theblacklist
    template: blacklist-persistent
  name: theblacklist
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations: null
  creationTimestamp: null
  labels:
    app: mysql
    template: blacklist-persistent
  name: mysql
spec:
  lookupPolicy:
    local: false
