apiVersion: v1
kind: Service
metadata:
  labels:
    app: theblacklist
    template: blacklist-persistent
  name: theblacklist
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: theblacklist
---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: mysql
    template: blacklist-persistent
  name: mysql
spec:
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    deployment: mysql
status:
  loadBalancer: {}
